# This file will be edited (the {{{ }}} things), and written to `emscripten.conf`
# when emscripten is first used and no config file is found.

# Any config setting <KEY> in this file can be overridden by setting the
# EM_<KEY> environment variable. For example, setting EM_LLVM_ROOT overrides
# the setting in this file.

LLVM_ROOT = {{{ LLVM_ROOT }}}
BINARYEN_ROOT = {{{ BINARYEN_ROOT }}}

# Location of the node binary to use for running the JS parts of the compiler.
# This engine must exist, or nothing can be compiled.
NODE_JS = {{{ NODE }}}
